### DISCUSSION TITLE
pnpm installs locally but not during build

### DISCUSSION THREAD

**Discussion by isaacfink** [railwayapp/nixpacks#1143] [Q&A]
During install I am getting this error
```text
ERR_PNPM_WORKSPACE_PKG_NOT_FOUND
```
Because the install command needs to run from the root but the build and serve commands should run from a subdirectory, is there a way to accomplish this?

**Comment by tamish-max** [comment]
Yes — this is a common monorepo/pnpm mismatch. `pnpm install` wants the workspace root, while build/start often need to run from the app subdirectory.

The cleanest fix is usually:

- keep the **build context at the repo root** so `pnpm-workspace.yaml` and the lockfile are visible
- use filters or `-C` to target the sub-app for build/start

For example:

```toml
[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter ./apps/web... build"]

[start]
cmd = "pnpm --filter ./apps/web... start"
```

or:

```toml
[phases.build]
cmds = ["pnpm -C apps/web build"]

[start]
cmd = "pnpm -C apps/web start"
```

The important part is that the install step still sees the workspace root. If you point the whole build at the subdirectory too early, pnpm loses the workspace context and you get `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND`.

So: root for install, targeted subdir/filter for build + start.
