### DISCUSSION TITLE
GitHub Actions Build Cache

### DISCUSSION THREAD

**Discussion by henrikbjorn** [railwayapp/nixpacks#828] [Q&A]
Is there a way to persist cache between builds on Github Actions and Nixpacks.

I am using GitHub Actions to deploy to fly

My workflow looks like this:

``` yaml
---
name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only --nixpacks
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```
