### ISSUE TITLE
Bun 1.1 - Nixpacks Feature Request

### ISSUE THREAD

**Issue by benjamint08** [railwayapp/nixpacks#1093]
### Feature request

Bun 1.1.5 is currently the newest version of Bun. Nixpacks currently uses Bun 1.0 which lacks a LOT of features that 1.1 introduced, such as Globs which are a crucial part of the Bun apps I build, like ProBun.

### Motivation

I host my apps on Coolify and writing Dockerfiles for each Bun app to use 1.1 is a pain - if Nixpacks supported the newest versions then I wouldn't have to do this. Thank you so much to anyone that sees this.

**Comment by brody192** [comment]
You can get nixpacks to use bun 1.1.4 by adding a nixpacks.toml file to your project -
```toml
[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = 'd05592ea7e9656648093dfe0e817819486bd5054' # https://github.com/NixOS/nixpkgs/commit/d05592ea7e9656648093dfe0e817819486bd5054
```
