### ISSUE TITLE
Double quotes string environment does not work when others are single

### ISSUE THREAD

**Issue by Thijmen** [railwayapp/nixpacks#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So, given following toml:

```toml
providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1722297819'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
DUMMY_ENV_VAR = "test"
[phases.build]
dependsOn = ['install']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_18',
    'npm-9_x',
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'bdd2f439c62aa0b8aa97f5c784a965c23f968fe6'

[start]
cmd = 'npm run start'
```

This will build, however the environment variable `DUMMY_ENV_VAR` will be empty in the image. 

When doing single quote, it will work. Is this a bug in Nixpacks? When I lint the toml (https://www.toml-lint.com/), it is valid toml.

### Environment

MacOS, nixpacks 1.26.0
