### ISSUE TITLE
Nixpacks Feature Request: Expose ability to use additional CA certs

### ISSUE THREAD

**Issue by joewrightfd** [railwayapp/nixpacks#1211]
### Feature request

When I run `nixpacks` I get failures as my company uses a MITM security tool that breaks http calls. It'd be good if you could specify an additional CA like:

```toml
[security.pki]
  certificateFiles = ["/opt/certs/cert_combined.pem"]
```

### Motivation

Ability to use nixpacks inside corporate networks.
