### ISSUE TITLE
Feat: Bump Bun to v1.2

### ISSUE THREAD

**Issue by cliffordkleinsr** [railwayapp/nixpacks#1212]
### Feature request

:) if its possible

**Comment by ansh** [comment]
Yes this would be great since this PR was already merged to detect bun's text-based lockfiles https://github.com/railwayapp/nixpacks/issues/1248 https://github.com/railwayapp/nixpacks/pull/1245

@coffee-cup

**Comment by TheMikeyRoss** [comment]
I thought it was a nixpkgs issue but they directed me here

**Comment by coffee-cup** [comment]
You can use Bun 1.2 by manually setting the nix package archive in a `nixpacks.toml` file

```toml
[phases.setup]
nixpkgsArchive = "477d26d111feea02901d740cb4b9cae3b679e8d9"
```

We are a bit hesitant to update this globally since it would also update the default NodeJS version
