### ISSUE TITLE
bundler: not executable: bin/rails (Rails deployment railwayapp)

### ISSUE THREAD

**Issue by saied2035** [railwayapp/nixpacks#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I started using the railway app yesterday and I liked it. However, for some reason, if I deploy my rails app with Nixpacks it gives this error in the deploy tab `bundler: not executable: bin/rails` like this:

![Screenshot 2022-11-08 112813](https://user-images.githubusercontent.com/70805060/200527438-182aa27f-f0b9-4b73-aa3b-49b4a715ba89.jpg)

The website deployed successfully when I used Heroku Buildpacks.

Does anyone know how to solve this issue?

### Environment

operating system: windows 10
Rails version:  7.0.3
Ruby version:  3.1.2p20
Node version: 16.16.0
npm version: 8.13.2
yarn version: 1.22.19

**Comment by coffee-cup** [comment]
Can you please share the build logs and if possible a repo that is failing to deploy.

**Comment by saied2035** [comment]
@coffee-cup  I tried to get the whole logs or copy it but I can't.

This is my repo: https://github.com/saied2035/Rails-budget-app

Thanks in advance.

**Comment by coffee-cup** [comment]
Was the project built with Windows? It looks like the binary (`bin/rails`) is not in the expected format

**Comment by coffee-cup** [comment]
Ah yes, the buildpacks do this to handle Windows
![image](https://user-images.githubusercontent.com/3044853/200641791-08f07ab7-2676-43b5-bbae-8df45fcc204a.png)

Nixpacks should do something similar

**Comment by saied2035** [comment]
@coffee-cup Thanks for your explanation. Is there any temporary solution till This problem gets fixed?

**Comment by coffee-cup** [comment]
Yes, in the meantime you can add a `nixpacks.toml` file to the repo with the contents

```toml
[phases.install]
cmds = ["rm -rf bin", "..."]
```
 and Nixpacks will not use the Windows binaries.

This isn't the greatest solution and I am working on a fix to Nixpacks that should handle this automatically.

**Comment by coffee-cup** [comment]
I believe I have a workaround, which is to update the start command so it doesn't use the local binaries. You can do that by creating a `nixpacks.toml` file in the app root with the contents

```toml
[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000} -e $RAILS_ENV"
```

This is obviously not an ideal solution and I am working on updating Nixpacks to handle this automatically.

**Comment by saied2035** [comment]
@coffee-cup  I tried it and the app worked but crashed after a while so I searched a bit and did the following in the `nixpacks.toml`:
```toml
[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000} -e $RAILS_ENV"
[variables]
RAILS_ENV = 'production'
```
but this still gives an error that the `secret_key_base` is missing. 

It can be added like this:
``` toml
[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000} -e $RAILS_ENV"
[variables]
RAILS_ENV = 'production'
SECRET_KEY_BASE = 'your secret key base'
```
but this is not good if I will upload the toml file

I added the secret_key_base to the variables in the railway app like this instead:

![Screenshot 2022-11-09 112842](https://user-images.githubusercontent.com/70805060/200792727-54d717e7-ed5c-4a96-b943-fe7d73044a63.jpg)

Now the project got deployed successfully.

*note*: the deployment only becomes successful when I deploy with the railway cli.
