### ISSUE TITLE
Support changing timezone

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#794]
### Feature request

Support changing the timezone on the running machine via an environment variable

### Motivation

This would allow users to change the timezone of their project

**Comment by matteyahmed** [comment]
this would be a really helpful feature

**Comment by coffee-cup** [comment]
This could be added as a provider. Something simple that just runs a few commands to change the default timezone. Then all you would have to do to use it would be

```toml
providers = ["...", "timezone"]

[variables]
TZ = "..."
```
