### ISSUE TITLE
nixpacks relies on outdated version of `deno` and other packages

### ISSUE THREAD

**Issue by ifiokjr** [railwayapp/nixpacks#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Attempting to use an up to date version of `Deno` results in an error. 

I'm trying to use [this feature released in January](https://deno.com/blog/v1.30#denojson-becomes-an-import-map) which allows the `deno.jsonc` file to be used in lieu of an `import_map.json`.

Unfortunately the version of deno is not supported wiva nix pkgs. 

To fix this, the version of `nixpkgs` being used will need to be updated.

https://github.com/railwayapp/nixpacks/blob/ec545bbd725d6c2a6cab9031d22e60bc798178f3/src/nixpacks/nix/mod.rs#L8-L11

I'm not sure how feasible it is. 

### To reproduce

Running the following file structure will fail with the following error.

```markup
error: Relative import path "~" not prefixed with / or ./ or ../
```

##### `deno.jsonc`

```jsonc
{
  "imports": {
    "~/": "./"
  }
}
```

##### `mod.ts`

```ts
import { print } from '~/local.ts';
print();
```

##### `local.ts`

```ts
export function print() {
  console.log("i PriNt gOoD");
}
```

##### `nixpacks.toml`

```toml
[phases.setup]
nixPkgs = ["...", "deno"]

[start]
cmd = "deno run mod.ts"
```

### Environment

This fails while using nixpacks on `railway.app`.

Locally, I'm running macos Ventura 13.2.1, and nixpacks 1.4.1.

**Comment by coffee-cup** [comment]
Yes this is known. We are looking into ways of gracfully updating the Nixpkg archive without breaking existing builds that rely on the current default versions.

In the meantime, you can update the archive version specific to your app https://nixpacks.com/docs/configuration/file#nixpkgs-archive

Something like

```toml
[phases.setup]
nixPkgs = ["...", "deno"]
nixpkgsArchive = "293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847"

[start]
cmd = "deno run mod.ts"
```
